import { projects, type Lang } from '@/lib/projects';
import { Education } from '@/components/education';
import { LandscapeStudy } from '@/components/landscape-study';
import { ActionLink } from '@/components/action-link';
const tr=(lang:Lang,en:string,pt:string)=>lang==='pt'?pt:en;
const path=(lang:Lang)=>lang==='pt'?'/pt':'';
export function Header({lang,slug}:{lang:Lang;slug?:string}){const base=path(lang),alternate=lang==='en'?'/pt':'';return <><a className="skip-link" href="#main">{tr(lang,'Skip to content','Pular para o conteúdo')}</a><header className="site-header"><a className="wordmark" href={base||'/'} aria-label="Otávio Ramos — home">otávio ramos<span>↗</span></a><nav aria-label={tr(lang,'Main navigation','Navegação principal')}><a href={base+'/#work'}>{tr(lang,'Work','Projetos')}</a><a href={base+'/#about'}>{tr(lang,'About','Sobre')}</a><a className="language-link" href={alternate+(slug?'/work/'+slug:'/')} hrefLang={lang==='en'?'pt-BR':'en'}>{lang==='en'?'PT':'EN'} <span aria-hidden="true">↗</span></a></nav></header></>}
export function Footer({lang}:{lang:Lang}){return <footer id="contact" className="site-footer"><div className="section-label"><span>03 / {tr(lang,'NEXT CONVERSATION','PRÓXIMA CONVERSA')}</span><span>{tr(lang,'BASED IN BRAZIL','NO BRASIL')}</span></div><a className="contact-title" href="mailto:otavio.fr1@gmail.com">{tr(lang,'Let’s build','Vamos criar')}<br/><span>{tr(lang,'what’s next.','o próximo passo.')} ↗</span></a><div className="footer-bottom"><a href="mailto:otavio.fr1@gmail.com">otavio.fr1@gmail.com</a><div><a href="https://www.linkedin.com/in/otaviofr/">LinkedIn ↗</a><a href="https://github.com/otavioframos">GitHub ↗</a><a href={path(lang)+'/#main'}>{tr(lang,'Back to top ↑','Voltar ao topo ↑')}</a></div><p>© 2026 Otávio Ramos</p></div></footer>}
export function ProjectVisual({project,detail=false,lang='en'}:{project:typeof projects[number];detail?:boolean;lang?:Lang}){return <div className={'project-visual '+project.theme+(detail?' detail-visual':'')}>
{project.slug==='mindyoung'?<><div className="visual-word"><span className="eyebrow">{tr(lang,'A CURIOUS MIND','UMA MENTE CURIOSA')}</span><strong>Mind<br/>Young.</strong><img className="owl" src="/images/mindyoung-owl.webp" alt="" width="512" height="512" loading="lazy"/></div><img className="mind-screen" src={project.image} alt={project[lang].caption} width="780" height="1688" loading={detail?'eager':'lazy'}/></>:<img className="landscape" src={project.image} alt={project[lang].caption} width={project.slug==='avela'?1920:1440} height={project.slug==='avela'?1080:1024} loading="lazy"/>}
<span className="image-corner" aria-hidden="true">↗</span></div>}
export function Portfolio({lang}:{lang:Lang}){return <div className="portfolio-home" lang={lang==='pt'?'pt-BR':'en'}><Header lang={lang}/><main id="main">
<section className="nature-hero">
  <LandscapeStudy lang={lang}/>
  <div className="hero-intro">
    <p className="hero-kicker">{tr(lang,'BASED IN BRAZIL / EN + PT','NO BRASIL / PT + EN')}</p>
    <h1>Otávio Ramos<span>.</span></h1>
    <p className="hero-role">{tr(lang,'Product design for','Product design para')}<br/><span>{tr(lang,'consumer apps & AI.','apps B2C e IA.')}</span></p>
    <p className="hero-position">{tr(lang,'Sole designer at A3Lab. Connecting strategy, interfaces, and development—from the first idea to the product people use.','Único designer da A3Lab. Conectando estratégia, interfaces e desenvolvimento — da primeira ideia ao produto que as pessoas usam.')}</p>
    <div className="hero-actions"><ActionLink href="#work" label={tr(lang,'View selected work','Ver projetos')}/><ActionLink href="mailto:otavio.fr1@gmail.com" label={tr(lang,'Let’s talk','Vamos conversar')} secondary/></div>
    <p className="hero-philosophy">{tr(lang,'Designing experiences. Interfaces are the consequence.','Projetando experiências. Interfaces são a consequência.')}</p>
  </div>
  <div className="personal-notes">
    <article><span className="note-index">01 / {tr(lang,'NOW','AGORA')}</span><h2>{tr(lang,'Currently','Atualmente')}</h2><p>{tr(lang,'Designing consumer apps at A3Lab. Connecting brand, product, and development from the studio’s earliest days.','Projetando apps B2C na A3Lab. Conectando marca, produto e desenvolvimento desde o início do estúdio.')}</p></article>
    <article><span className="note-index">02 / {tr(lang,'PERSPECTIVE','PERSPECTIVA')}</span><h2>{tr(lang,'What I care about','O que me move')}</h2><p>{tr(lang,'How a product fits into an ordinary day. The small decisions that make an experience feel useful, clear, and worth returning to.','Como um produto faz parte de um dia comum. As pequenas decisões que tornam uma experiência útil, clara e boa de revisitar.')}</p></article>
    <article><span className="note-index">03 / {tr(lang,'OFF THE CLOCK','ALÉM DO TRABALHO')}</span><h2>{tr(lang,'My daily fuel','Meu combustível')}</h2><p>{tr(lang,'Dialing in a V60, exploring creative coding, and following an idea into one more Figma tab. Curious about the craft, on and off screen.','Ajustando o V60, explorando creative coding e seguindo uma ideia até mais uma aba do Figma. Curioso sobre o fazer, dentro e fora das telas.')}</p></article>
  </div>
</section>
<section id="work" className="work-index"><div className="work-introduction"><div><p className="eyebrow">01 / {tr(lang,'SELECTED WORK','PROJETOS SELECIONADOS')}</p><h2>{tr(lang,'Ideas, made real.','Ideias que ganham vida.')}</h2></div><p>{tr(lang,'A closer look at the products, systems, and decisions I’ve helped shape.','Um olhar para os produtos, sistemas e decisões que ajudei a construir.')}</p></div><div className="project-grid">{projects.map(p=><article className="project" key={p.slug}><div className="project-heading"><div><p className="eyebrow">{p.number} / {p[lang].category}</p><h2><a href={path(lang)+'/work/'+p.slug}>{p.name}</a></h2></div><p>{p[lang].summary}</p></div><a className="visual-link" href={path(lang)+'/work/'+p.slug} aria-label={tr(lang,'Read the '+p.name+' case study','Ler o case '+p.name)}><ProjectVisual project={p} lang={lang}/></a><div className="project-meta"><span>{p[lang].scope}</span><ActionLink href={path(lang)+'/work/'+p.slug} label={tr(lang,'View project','Ver projeto')} secondary/></div></article>)}</div></section>
<section id="about" className="about-section"><div className="section-label"><span>02 / {tr(lang,'THE PERSON BEHIND THE WORK','A PESSOA POR TRÁS DO TRABALHO')}</span><span>OTÁVIO RAMOS</span></div><div className="about-grid"><h2>{tr(lang,'Design the product.','Projetar o produto.')}<br/><em>{tr(lang,'Understand the system.','Entender o sistema.')}</em></h2><div className="about-copy"><p>{tr(lang,'I helped establish A3Lab, A3Media’s consumer-app R&D studio. As its sole designer, I work across brand positioning, the studio’s first two consumer products, and internal tools, collaborating closely with development.','Participei da criação da A3Lab, estúdio de pesquisa e desenvolvimento de apps B2C da A3Media. Como único designer, atuo no posicionamento da marca, nos dois primeiros produtos e nas ferramentas internas, em parceria com desenvolvimento.')}</p><p>{tr(lang,'My background in UX/UI and acquisition connects how people discover a product with what happens when they use it. I also helped establish the team’s work-management process using Linear, Notion, Codex, and Fireflies.ai.','Minha experiência em UX/UI e aquisição conecta como as pessoas descobrem um produto ao que acontece quando o utilizam. Também ajudei a estruturar a gestão de tarefas do time com Linear, Notion, Codex e Fireflies.ai.')}</p><p>{tr(lang,'I’m studying Systems Analysis and Development at FIAP, bringing a deeper technical understanding into my design practice. Comfortable working in English; open to discussing international opportunities.','Curso Análise e Desenvolvimento de Sistemas na FIAP para aprofundar minha compreensão técnica. Tenho facilidade para trabalhar em inglês e interesse em oportunidades internacionais.')}</p><p className="creative-note">{tr(lang,'I’m drawn to creative coding: exploring how motion, interaction, and tools like GSAP can give an interface its own character.','Tenho um interesse especial por creative coding: explorar como movimento, interação e ferramentas como GSAP podem dar personalidade a uma interface.')}</p><a className="text-link" href="https://www.linkedin.com/in/otaviofr/">{tr(lang,'Experience & background','Experiência e formação')} ↗</a></div></div><div className="principles"><div><span className="eyebrow">01 / {tr(lang,'OWNERSHIP','RESPONSABILIDADE')}</span><p>{tr(lang,'Brand, product, and the connections between them.','Marca, produto e as conexões entre eles.')}</p></div><div><span className="eyebrow">02 / {tr(lang,'COLLABORATION','COLABORAÇÃO')}</span><p>{tr(lang,'Work through the details with development.','Resolver os detalhes junto a desenvolvimento.')}</p></div><div><span className="eyebrow">03 / {tr(lang,'BUILDING','CONSTRUÇÃO')}</span><p>{tr(lang,'Take an idea beyond the prototype.','Levar uma ideia além do protótipo.')}</p></div></div><Education lang={lang}/></section></main><Footer lang={lang}/></div>}
export function CaseStudy({slug,lang}:{slug:string;lang:Lang}){const p=projects.find(p=>p.slug===slug);if(!p)return null;const c=p[lang],next=projects[(projects.indexOf(p)+1)%projects.length];return <div lang={lang==='pt'?'pt-BR':'en'}><Header lang={lang} slug={slug}/><main id="main" className="case-main"><a className="back-link" href={path(lang)+'/#work'}>← {tr(lang,'Selected work','Projetos selecionados')}</a><section className="case-intro"><p className="eyebrow">{p.number} / {c.category} / 2026</p><h1>{p.name}<span className="accent-dot">.</span></h1><h2>{c.title}</h2><dl className="case-facts"><div><dt>{tr(lang,'MY ROLE','MEU PAPEL')}</dt><dd>{c.role}</dd></div><div><dt>{tr(lang,'SCOPE','ESCOPO')}</dt><dd>{c.scope}</dd></div><div><dt>STATUS</dt><dd>{c.status}</dd></div></dl></section><figure className="case-cover"><ProjectVisual project={p} detail lang={lang}/><figcaption>{c.caption}</figcaption></figure><div className="case-lead"><span className="eyebrow">{tr(lang,'THE CONTEXT','O CONTEXTO')}</span><p>{c.lead}</p></div>{c.sections.map((s,i)=><section className="case-section" key={s.label}><div className="case-section-grid"><p className="eyebrow">{s.label}</p><div><h2>{s.title}</h2><p>{s.body}</p>{'points' in s&&<ul>{s.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></div>{i===1&&<figure className={'case-extra '+p.theme}><img src={p.extra} alt={c.extraCaption} width={p.slug==='mindyoung'?512:p.slug==='avela'?1920:1440} height={p.slug==='mindyoung'?512:p.slug==='avela'?1080:1024} loading="lazy"/><figcaption>{c.extraCaption}</figcaption></figure>}</section>)}<section className="case-outcome"><p className="eyebrow">{tr(lang,'WHERE THE WORK STANDS','ONDE O TRABALHO CHEGOU')}</p><p>{c.outcome}</p>{p.url&&<a className="text-link" href={p.url}>{tr(lang,'Visit the product','Visitar o produto')} ↗</a>}</section><a className="next-project" href={path(lang)+'/work/'+next.slug}><span className="eyebrow">{tr(lang,'NEXT PROJECT','PRÓXIMO PROJETO')}</span><span>{next.name} ↗</span></a></main><Footer lang={lang}/></div>}
