import { projects, type Lang } from '@/lib/projects';
import { SelectedWork } from '@/components/selected-work';
import { MoreWork } from '@/components/more-work';
import { Education } from '@/components/education';
import { LandscapeStudy } from '@/components/landscape-study';
import { ActionLink } from '@/components/action-link';
const tr=(lang:Lang,en:string,pt:string)=>lang==='pt'?pt:en;
const path=(lang:Lang)=>lang==='pt'?'/pt':'';
export function Header({lang,slug}:{lang:Lang;slug?:string}){const base=path(lang),alternate=lang==='en'?'/pt':'';return <><a className="skip-link" href="#main">{tr(lang,'Skip to content','Pular para o conteúdo')}</a><header className="site-header"><a className="wordmark" href={base||'/'} aria-label="Otávio Ramos — home">otávio ramos<span>↗</span></a><nav aria-label={tr(lang,'Main navigation','Navegação principal')}><a href={base+'/#work'}>{tr(lang,'Work','Projetos')}</a><a href={base+'/#about'}>{tr(lang,'About','Sobre')}</a><a className="language-link" href={alternate+(slug?'/work/'+slug:'/')} hrefLang={lang==='en'?'pt-BR':'en'}>{lang==='en'?'PT':'EN'} <span aria-hidden="true">↗</span></a></nav></header></>}
export function Footer({lang}:{lang:Lang}){return <footer id="contact" className="site-footer"><div className="section-label"><span>03 / {tr(lang,'NEXT CONVERSATION','PRÓXIMA CONVERSA')}</span><span>{tr(lang,'BASED IN BRAZIL','NO BRASIL')}</span></div><a className="contact-title" href="mailto:otavio.fr1@gmail.com">{tr(lang,'Have something in mind?','Tem algo em mente?')}<br/><span>{tr(lang,'Let’s talk.','Vamos conversar.')}</span></a><div className="footer-bottom"><a href="mailto:otavio.fr1@gmail.com">otavio.fr1@gmail.com</a><div><a href="https://www.linkedin.com/in/otaviofr/">LinkedIn ↗</a><a href="https://github.com/otavioframos">GitHub ↗</a><a href={path(lang)+'/#main'}>{tr(lang,'Back to top ↑','Voltar ao topo ↑')}</a></div><p>© 2026 Otávio Ramos</p></div></footer>}
export function ProjectVisual({project,detail=false,lang='en'}:{project:typeof projects[number];detail?:boolean;lang?:Lang}){
if(project.slug==='mindyoung'&&!detail)return <div className="project-visual mindyoung mind-preview">
  <div className="mind-preview-brand">
    <div><span className="mind-preview-label">{tr(lang,'A CURIOUS MIND','UMA MENTE CURIOSA')}</span><strong>MindYoung.</strong></div>
    <img src="/images/mindyoung-owl.webp" alt="" width="512" height="512" loading="lazy"/>
    <span className="mind-preview-caption">{tr(lang,'Cognitive training, daily.','Treino cognitivo, todo dia.')}</span>
  </div>
  <img className="mind-preview-screen" src={project.image} alt={project[lang].caption} width="780" height="1688" loading="lazy"/>
  <span className="image-corner" aria-hidden="true">↗</span>
</div>;
return <div className={'project-visual '+project.theme+(detail?' detail-visual':'')}>
{project.slug==='mindyoung'?<><div className="visual-word"><span className="eyebrow">{tr(lang,'A CURIOUS MIND','UMA MENTE CURIOSA')}</span><strong>Mind<br/>Young.</strong><img className="owl" src="/images/mindyoung-owl.webp" alt="" width="512" height="512" loading="lazy"/></div><img className="mind-screen" src={project.image} alt={project[lang].caption} width="780" height="1688" loading={detail?'eager':'lazy'}/></>:<img className="landscape" src={project.image} alt={project[lang].caption} width={project.slug==='avela'?1920:1440} height={project.slug==='avela'?1080:1024} loading="lazy"/>}
<span className="image-corner" aria-hidden="true">↗</span></div>}
export function Portfolio({lang}:{lang:Lang}){return <div className="portfolio-home" lang={lang==='pt'?'pt-BR':'en'}><Header lang={lang}/><main id="main">
<section className="nature-hero">
  <LandscapeStudy lang={lang}/>
  <div className="hero-intro">
    <p className="hero-kicker">{tr(lang,'FOUNDING PRODUCT DESIGNER / BRAZIL','FOUNDING PRODUCT DESIGNER / BRASIL')}</p>
    <h1>Otávio Ramos<span>.</span></h1>
    <p className="hero-position">{tr(lang,'I design apps at A3Lab. Lately, I’ve been spending more time with AI and creative coding.','Sou designer na A3Lab. Ultimamente, tenho dedicado mais tempo a IA e creative coding.')}</p>
    <div className="hero-actions"><ActionLink href="#work" label={tr(lang,'See my work','Ver projetos')}/><ActionLink href="mailto:otavio.fr1@gmail.com" label={tr(lang,'Get in touch','Conversar')} secondary/></div>
    <p className="hero-location">{tr(lang,'Open to relocation with visa support.','Aberto a conversar sobre mudança de país com apoio para o visto.')}</p>
  </div>

</section>
<section id="work" className="work-index"><div className="work-introduction"><div><p className="eyebrow">01 / {tr(lang,'SELECTED WORK','PROJETOS SELECIONADOS')}</p><h2>{tr(lang,'Selected work','Projetos selecionados')}</h2></div><p>{tr(lang,'Consumer apps and tools I’ve worked on at A3Lab.','Apps B2C e ferramentas em que trabalhei na A3Lab.')}</p></div><SelectedWork items={projects.map(p=>({slug:p.slug,name:p.name,category:p[lang].category,summary:p[lang].summary,image:p.image,href:path(lang)+'/work/'+p.slug}))} label={tr(lang,'View project','Ver projeto')}/></section>
<MoreWork lang={lang}/>
<section id="about" className="about-section"><div className="section-label"><span>02 / {tr(lang,'THE PERSON BEHIND THE WORK','A PESSOA POR TRÁS DO TRABALHO')}</span><span>OTÁVIO RAMOS</span></div><div className="about-grid"><h2 className="about-heading">{tr(lang,'A bit about me.','Um pouco sobre mim.')}</h2><figure className="about-portrait"><img src="/images/otavio-portrait.png" alt="Otávio Ramos" width="1080" height="1350" loading="lazy" decoding="async"/></figure><div className="about-copy"><p>{tr(lang,'I’m the founding product designer at A3Lab, A3Media’s consumer-app studio. I joined at its launch and remain the only designer on the team. My work includes the brand, our first two apps, and internal tools.','Sou Founding Product Designer na A3Lab, estúdio de apps B2C da A3Media. Entrei na criação do estúdio e continuo sendo o único designer do time. Trabalho na marca, nos dois primeiros apps e em ferramentas internas.')}</p><p>{tr(lang,'My background in UX/UI and acquisition connects how people discover a product with what happens when they use it. I also helped establish the team’s work-management process using Linear, Notion, Codex, and Fireflies.ai.','Minha experiência em UX/UI e aquisição conecta como as pessoas descobrem um produto ao que acontece quando o utilizam. Também ajudei a estruturar a gestão de tarefas do time com Linear, Notion, Codex e Fireflies.ai.')}</p><p>{tr(lang,'I’m studying Systems Analysis and Development at FIAP, bringing a deeper technical understanding into my design practice. Comfortable working in English; open to discussing international opportunities.','Curso Análise e Desenvolvimento de Sistemas na FIAP para aprofundar minha compreensão técnica. Tenho facilidade para trabalhar em inglês e interesse em oportunidades internacionais.')}</p><p className="creative-note">{tr(lang,'Outside product work, I like experimenting with motion, creative coding, and GSAP. This site is one place to try those ideas.','Além do trabalho com produto, gosto de experimentar com movimento, creative coding e GSAP. Este site é um lugar para testar essas ideias.')}</p><a className="text-link" href="https://www.linkedin.com/in/otaviofr/">{tr(lang,'Experience & background','Experiência e formação')} ↗</a></div></div><div className="about-notes">
  <section className="working-style" aria-labelledby="working-style-title">
    <h3 id="working-style-title" className="eyebrow">{tr(lang,'HOW I WORK','COMO TRABALHO')}</h3>
    <dl>
      <div><dt>{tr(lang,'Ownership','Responsabilidade')}</dt><dd>{tr(lang,'Brand, product, and the connections between them.','Marca, produto e as conexões entre eles.')}</dd></div>
      <div><dt>{tr(lang,'Collaboration','Colaboração')}</dt><dd>{tr(lang,'Work through the details with development.','Resolver os detalhes junto a desenvolvimento.')}</dd></div>
      <div><dt>{tr(lang,'Building','Construção')}</dt><dd>{tr(lang,'Take an idea beyond the prototype.','Levar uma ideia além do protótipo.')}</dd></div>
    </dl>
  </section>
  <section className="personal-perspective" aria-labelledby="perspective-title">
    <h3 id="perspective-title" className="eyebrow">{tr(lang,'WHAT I CARE ABOUT','O QUE ME MOVE')}</h3>
    <p className="perspective-statement">{tr(lang,'Making things that are easy to understand and useful in everyday life.','Fazer coisas fáceis de entender e úteis no dia a dia.')}</p>
    <div className="off-clock"><h4>{tr(lang,'Off the clock','Além do trabalho')}</h4><p>{tr(lang,'Coffee, creative coding, and the occasional late night in Figma.','Café, creative coding e uma ou outra noite até tarde no Figma.')}</p></div>
  </section>
</div><Education lang={lang}/></section></main><Footer lang={lang}/></div>}
export function CaseStudy({slug,lang}:{slug:string;lang:Lang}){const p=projects.find(p=>p.slug===slug);if(!p)return null;const c=p[lang],next=projects[(projects.indexOf(p)+1)%projects.length];return <div lang={lang==='pt'?'pt-BR':'en'}><Header lang={lang} slug={slug}/><main id="main" className="case-main"><a className="back-link" href={path(lang)+'/#work'}>← {tr(lang,'Selected work','Projetos selecionados')}</a><section className="case-intro"><p className="eyebrow">{p.number} / {c.category} / 2026</p><h1>{p.name}<span className="accent-dot">.</span></h1><h2>{c.title}</h2><dl className="case-facts"><div><dt>{tr(lang,'MY ROLE','MEU PAPEL')}</dt><dd>{c.role}</dd></div><div><dt>{tr(lang,'SCOPE','ESCOPO')}</dt><dd>{c.scope}</dd></div><div><dt>STATUS</dt><dd>{c.status}</dd></div></dl></section><figure className="case-cover"><ProjectVisual project={p} detail lang={lang}/><figcaption>{c.caption}</figcaption></figure><div className="case-lead"><span className="eyebrow">{tr(lang,'THE CONTEXT','O CONTEXTO')}</span><p>{c.lead}</p></div>{c.sections.map((s,i)=><section className="case-section" key={s.label}><div className="case-section-grid"><p className="eyebrow">{s.label}</p><div><h2>{s.title}</h2><p>{s.body}</p>{'points' in s&&<ul>{s.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></div>{i===1&&<figure className={'case-extra '+p.theme}><img src={p.extra} alt={c.extraCaption} width={p.slug==='mindyoung'?512:p.slug==='avela'?1920:1440} height={p.slug==='mindyoung'?512:p.slug==='avela'?1080:1024} loading="lazy"/><figcaption>{c.extraCaption}</figcaption></figure>}</section>)}<section className="case-outcome"><p className="eyebrow">{tr(lang,'WHERE THE WORK STANDS','ONDE O TRABALHO CHEGOU')}</p><p>{c.outcome}</p>{p.url&&<a className="text-link" href={p.url}>{tr(lang,'Visit the product','Visitar o produto')} ↗</a>}</section><a className="next-project" href={path(lang)+'/work/'+next.slug}><span className="eyebrow">{tr(lang,'NEXT PROJECT','PRÓXIMO PROJETO')}</span><span>{next.name} ↗</span></a></main><Footer lang={lang}/></div>}
